/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_TOKENS 64

enum token_type {
	TOKEN_NUM = 0,
	TOKEN_OP = 1,
};
typedef enum token_type token_type;

struct token {
	token_type type;
	union {
		double num;
		int op;
	} token_u;
};
typedef struct token token;

typedef struct {
	u_int expr_len;
	token *expr_val;
} expr;

struct calc_res {
	int errnum;
	union {
		double res;
	} calc_res_u;
};
typedef struct calc_res calc_res;

#define CALCPROG 0x20000001
#define CALCVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULADORA 1
extern  calc_res * calculadora_1(expr , CLIENT *);
extern  calc_res * calculadora_1_svc(expr , struct svc_req *);
extern int calcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULADORA 1
extern  calc_res * calculadora_1();
extern  calc_res * calculadora_1_svc();
extern int calcprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_token_type (XDR *, token_type*);
extern  bool_t xdr_token (XDR *, token*);
extern  bool_t xdr_expr (XDR *, expr*);
extern  bool_t xdr_calc_res (XDR *, calc_res*);

#else /* K&R C */
extern bool_t xdr_token_type ();
extern bool_t xdr_token ();
extern bool_t xdr_expr ();
extern bool_t xdr_calc_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
