/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

calc_res *
calculadora_1_svc(expr expr,  struct svc_req *rqstp)
{
	static calc_res  result;

	/*
	 * insert server code here
	 */

	double          stack[MAX_TOKENS];
    int             top = 0;
    double          a, b, res;

    xdr_free(xdr_calc_res, &result);
    memset(&result, 0, sizeof(result));
    result.errnum = 0;

    for (int i = 0; i < expr.expr_len; i++) {
        token *t = &expr.expr_val[i];

        if (t->type == TOKEN_NUM) {
            stack[top++] = t->token_u.num;
        } else {
            b = stack[--top];
            a = stack[--top];

            switch ((char)t->token_u.op) {
                case '+': 
					res = a + b; 
					break;

                case '-': 
					res = a - b; 
					break;

                case '*': 
					res = a * b; 
					break;

                case '/':
                    if (b == 0.0) { 
						result.errnum = 10;
						return &result; 
					}
                    res = a / b;
                    break;
            }
            stack[top++] = res;
        }
    }

    result.calc_res_u.res = stack[0];

	return &result;
}
