/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc.h"

bool_t
xdr_token_type (XDR *xdrs, token_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_token (XDR *xdrs, token *objp)
{
	register int32_t *buf;

	 if (!xdr_token_type (xdrs, &objp->type))
		 return FALSE;
	switch (objp->type) {
	case TOKEN_NUM:
		 if (!xdr_double (xdrs, &objp->token_u.num))
			 return FALSE;
		break;
	case TOKEN_OP:
		 if (!xdr_int (xdrs, &objp->token_u.op))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_expr (XDR *xdrs, expr *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->expr_val, (u_int *) &objp->expr_len, MAX_TOKENS,
		sizeof (token), (xdrproc_t) xdr_token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_calc_res (XDR *xdrs, calc_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errnum))
		 return FALSE;
	switch (objp->errnum) {
	case 0:
		 if (!xdr_double (xdrs, &objp->calc_res_u.res))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
