/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <errno.h>
#include <stdlib.h>

static int precedencia(char op)
{
    return (op == '*' || op == '/') ? 2 : 1;
}

static int shunting_yard(char *toks[], int n_toks, token output[])
{
    char op_stack[n_toks];
    int  op_top = 0;
    int  out_n  = 0;

    for (int i = 0; i < n_toks; i++) {
        char *t = toks[i];

        if (t[0] == '(') {
            op_stack[op_top++] = '(';

        } else if (t[0] == ')') {
            while (op_top > 0 && op_stack[op_top-1] != '(') {
                output[out_n].type       = TOKEN_OP;
                output[out_n].token_u.op = (int)op_stack[--op_top];
                out_n++;
            }
            if (op_top == 0) {
                fprintf(stderr, "Error: parentesis no balanceados\n");
                return -1;
            }
            op_top--;   /* descartar '(' */

        } else if (t[0]=='+' || t[0]=='-' || t[0]=='*' || t[0]=='/') {
            while (op_top > 0 &&
                   op_stack[op_top-1] != '(' &&
                   precedencia(op_stack[op_top-1]) >= precedencia(t[0])) {
                output[out_n].type       = TOKEN_OP;
                output[out_n].token_u.op = (int)op_stack[--op_top];
                out_n++;
            }
            op_stack[op_top++] = t[0];

        } else {
            output[out_n].type        = TOKEN_NUM;
            output[out_n].token_u.num = atof(t);
            out_n++;
        }
    }

    while (op_top > 0) {
        if (op_stack[op_top-1] == '(') {
            fprintf(stderr, "Error: parentesis no balanceados\n");
            return -1;
        }
        output[out_n].type       = TOKEN_OP;
        output[out_n].token_u.op = (int)op_stack[--op_top];
        out_n++;
    }

    return out_n;
}

void
calcprog_1(char *host, expr expr)
{
	CLIENT *clnt;
	calc_res  *result;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCPROG, CALCVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result = calculadora_1(expr, clnt);
	if (result == (calc_res *) NULL) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}

	if(result->errnum != 0) {
        errno = result->errnum;
        
        switch (errno)
        {
        case 10: /* division por cero */
            fprintf(stderr, "Error: division por cero\n");
            break;
        
        default:
            fprintf(stderr, "Error: %d\n", result->errnum);
            break;
        }

		exit(1);
	}
	
	printf("Resultado: %g\n", result->calc_res_u.res);

	xdr_free(xdr_calc_res, result);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main(int argc, char *argv[])
{
    static token  rpn_buf[MAX_TOKENS];
    static char  *toks[MAX_TOKENS];
    expr      expr;
    int           n_toks = 0, n_rpn;

    if (argc < 3) {
        printf("Uso: %s host \"expresion\"\n", argv[0]);
        exit(1);
    }

    if (strlen(argv[2]) == 0) {
        fprintf(stderr, "Error: la expresion no puede ser vacia\n");
        exit(1);
    }

    char *tok = strtok(argv[2], " \t");
    while (tok && n_toks < MAX_TOKENS) {
        toks[n_toks++] = tok;
        tok = strtok(NULL, " \t");
    }

    if (tok != NULL) {
        fprintf(stderr, "Error: la expresion supera el maximo de %d tokens\n", MAX_TOKENS);
        exit(1);
    }

    n_rpn = shunting_yard(toks, n_toks, rpn_buf);
    if (n_rpn <= 0) 
		exit(1);

    expr.expr_val = rpn_buf;
    expr.expr_len = n_rpn;

    calcprog_1(argv[1], expr);

    return 0;
}